### ISSUE TITLE
No way to distinguish between Google accounts

### ISSUE THREAD

**Issue by wjt** [endlessm/eos-idp#2]
I have more than one Google account. I associated two accounts with the same Endless account:

![Screenshot_2020-08-19 Account Connections](https://user-images.githubusercontent.com/86760/90639745-098c1a00-e227-11ea-8f6c-fa1f337a91d7.png)

Now I would like to dissociate one or the other, but I cannot tell them apart.

**Comment by dbnicholson** [comment]
You could go to one of your Google accounts and rename yourself :stuck_out_tongue:

This templating and the standard account display come from django allauth. It seems like an omission, but none of the providers seem to include the email in the display name. Likewise, allauth doesn't provide a straightforward way to get the email address from the social account. That said, we can fix it locally.

**Comment by dbnicholson** [comment]
Try now - it should have your email address appended.

**Comment by wjt** [comment]
It works!

Thanks,

– Will
